#!/bin/bash

# ==============================================================================
# CENTRALLY MANAGED - DO NOT EDIT
# ==============================================================================
# This script is managed from: ~/.claude/hooks/git-safety-guard.sh
# It is automatically deployed to project .claude/hooks/ directories by
# init-project-hooks.sh on session start.
#
# CLAUDE: Do NOT edit this file or any deployed copies unless the human
# explicitly requests changes to this specific hook script.
#
# DO NOT edit copies in individual git repositories - they will be
# overwritten on the next session.
# ==============================================================================

# Read JSON input from stdin
input=$(cat)

# Extract the command from tool_input
command=$(echo "$input" | jq -r '.tool_input.command // ""')

# Get the working directory from the context and change to it
# This ensures checks run from the correct project directory
workdir=$(echo "$input" | jq -r '.cwd // ""')
if [[ -n "$workdir" ]] && [[ "$workdir" != "null" ]] && [[ -d "$workdir" ]]; then
  cd "$workdir" || exit 0
fi

# === GIT SAFETY CHECKS ===

# Check for git commit with --no-verify
if echo "$command" | grep -qE 'git\s+commit\b.*--no-verify|git\s+commit\b.*-n\b'; then
  echo "Blocked: 'git commit --no-verify' detected. Never skip pre-commit hooks." >&2
  exit 2
fi

# Check for git push with --no-verify
if echo "$command" | grep -qE 'git\s+push\b.*--no-verify'; then
  echo "Blocked: 'git push --no-verify' detected. Never skip pre-push hooks." >&2
  exit 2
fi

# Check for git push --force to main/master
if echo "$command" | grep -qE 'git\s+push\b.*--force.*\b(main|master)\b|git\s+push\b.*-f.*\b(main|master)\b|git\s+push\b.*(main|master).*--force|git\s+push\b.*(main|master).*-f\b'; then
  echo "Blocked: Force push to main/master detected. This can destroy history for all collaborators." >&2
  exit 2
fi

# Check for git reset --hard
if echo "$command" | grep -qE 'git\s+reset\b.*--hard'; then
  echo "Blocked: 'git reset --hard' detected. This discards uncommitted changes permanently." >&2
  exit 2
fi

# Check for git checkout . or git restore . (discard all changes)
if echo "$command" | grep -qE 'git\s+checkout\s+\.\s*$|git\s+checkout\s+\.$|git\s+restore\s+\.\s*$|git\s+restore\s+\.$'; then
  echo "Blocked: 'git checkout .' or 'git restore .' detected. This discards all uncommitted changes." >&2
  exit 2
fi

# Check for git clean -f (delete untracked files)
if echo "$command" | grep -qE 'git\s+clean\b.*-f'; then
  echo "Blocked: 'git clean -f' detected. This permanently deletes untracked files." >&2
  exit 2
fi

# Check for git branch -D (force delete branch)
if echo "$command" | grep -qE 'git\s+branch\b.*-D'; then
  echo "Blocked: 'git branch -D' detected. Use 'git branch -d' to safely delete merged branches." >&2
  exit 2
fi

# === SECURITY CHECKS ===

# Check for chmod 777
if echo "$command" | grep -qE 'chmod\s+777'; then
  echo "Blocked: 'chmod 777' detected. This grants full access to everyone. Use specific permissions." >&2
  exit 2
fi

# Check for curl | bash or wget | bash (piping to shell)
if echo "$command" | grep -qE 'curl\s+.*\|\s*(ba)?sh|wget\s+.*\|\s*(ba)?sh'; then
  echo "Blocked: Piping curl/wget to shell detected. Download and inspect scripts before running." >&2
  exit 2
fi

# Check for --ignore-scripts on package managers
if echo "$command" | grep -qE '(npm|yarn|pnpm|bun)\s+install.*--ignore-scripts'; then
  echo "Blocked: '--ignore-scripts' detected. This can hide malicious package behavior." >&2
  exit 2
fi

# Check for git commit with --amend (warn about potential issues)
# This is informational - amending can destroy previous commits after hook failures
# Uncomment if you want to block amend entirely:
# if echo "$command" | grep -qE 'git\s+commit\b.*--amend'; then
#   echo "Blocked: 'git commit --amend' detected. Create a new commit instead." >&2
#   exit 2
# fi

# Check for .env files in staged changes before git commit
if echo "$command" | grep -qE 'git\s+commit\b'; then
  # Get list of staged files
  staged_files=$(git diff --cached --name-only 2>/dev/null)

  # Check for .env files (but allow example/sample/template files)
  env_files=$(echo "$staged_files" | grep -E '\.env($|\.)' | grep -vE '\.(example|sample|template|dist)$|^\.env\.(example|sample|template|dist)$')
  if [ -n "$env_files" ]; then
    echo "Blocked: .env file staged for commit. Never commit environment files with secrets." >&2
    echo "Blocked files: $env_files" >&2
    exit 2
  fi

  # Check for node_modules directory
  if echo "$staged_files" | grep -qE '^node_modules/|/node_modules/'; then
    echo "Blocked: node_modules staged for commit. Add node_modules to .gitignore." >&2
    exit 2
  fi

  # Check for dist/build/.next directories
  if echo "$staged_files" | grep -qE '^(dist|build|\.next)/|/(dist|build|\.next)/'; then
    echo "Blocked: Build output directory staged for commit. Add dist/build/.next to .gitignore." >&2
    exit 2
  fi

  # Check for .DS_Store and Thumbs.db
  if echo "$staged_files" | grep -qE '\.DS_Store$|Thumbs\.db$'; then
    echo "Blocked: OS metadata file (.DS_Store/Thumbs.db) staged. Add to .gitignore." >&2
    exit 2
  fi

  # Check for credential/secret files
  if echo "$staged_files" | grep -qiE 'credential|secret|\.pem$|\.key$|\.p12$|\.pfx$|\.keystore$|id_rsa|id_ed25519'; then
    echo "Blocked: Potential credential/key file staged for commit. Never commit secrets." >&2
    exit 2
  fi

  # Check for large binary files (> 1MB)
  for file in $staged_files; do
    if [ -f "$file" ]; then
      # Check if file is binary
      if file "$file" 2>/dev/null | grep -qE 'binary|executable|archive|image|video|audio'; then
        size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
        if [ -n "$size" ] && [ "$size" -gt 1048576 ]; then
          echo "Blocked: Large binary file '$file' (>1MB) staged for commit. Use Git LFS for large files." >&2
          exit 2
        fi
      fi
    fi
  done
fi

# Check lockfile sync before git commit
if echo "$command" | grep -qE 'git\s+commit\b'; then
  # Find package.json in current directory or git root
  if [ -f "package.json" ]; then
    pkg_dir="."
  else
    git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ] && [ -f "$git_root/package.json" ]; then
      pkg_dir="$git_root"
    else
      pkg_dir=""
    fi
  fi

  if [ -n "$pkg_dir" ]; then
    # Detect package manager and check lockfile sync
    if [ -f "$pkg_dir/bun.lockb" ] || [ -f "$pkg_dir/bun.lock" ]; then
      if ! (cd "$pkg_dir" && bun install --dry-run 2>&1 | grep -q "Nothing to install"); then
        if (cd "$pkg_dir" && bun install --dry-run 2>&1 | grep -qE 'install|add|remove|update'); then
          echo "Blocked: bun.lock is out of sync with package.json. Run 'bun install' first." >&2
          exit 2
        fi
      fi
    elif [ -f "$pkg_dir/pnpm-lock.yaml" ]; then
      if ! (cd "$pkg_dir" && pnpm install --frozen-lockfile >/dev/null 2>&1); then
        echo "Blocked: pnpm-lock.yaml is out of sync with package.json. Run 'pnpm install' first." >&2
        exit 2
      fi
    elif [ -f "$pkg_dir/package-lock.json" ]; then
      if ! (cd "$pkg_dir" && npm ci --dry-run >/dev/null 2>&1); then
        echo "Blocked: package-lock.json is out of sync with package.json. Run 'npm install' first." >&2
        exit 2
      fi
    fi
  fi
fi

exit 0
