#!/bin/bash

# ==============================================================================
# CENTRALLY MANAGED - DO NOT EDIT
# ==============================================================================
# This script is managed from: ~/.claude/hooks/typescript-quality-guard.sh
# It is automatically deployed to project .claude/hooks/ directories by
# init-project-hooks.sh on session start.
#
# CLAUDE: Do NOT edit this file or any deployed copies unless the human
# explicitly requests changes to this specific hook script.
#
# DO NOT edit copies in individual git repositories - they will be
# overwritten on the next session.
# ==============================================================================

# Read JSON input from stdin
input=$(cat)

# Extract file_path and content using jq
# Handle both Write (content) and Edit (new_string) tools
file_path=$(echo "$input" | jq -r '.tool_input.file_path // ""')
content=$(echo "$input" | jq -r '.tool_input.content // .tool_input.new_string // ""')

# Check for backwards compatibility re-exports (applies to all files)
if echo "$content" | grep -qiE 're-?export(ing|ed|s)?\s+(for|to\s+maintain|to\s+preserve|for\s+backward|for\s+backwards)\s+(backward|backwards)?\s*compatib'; then
  echo "Blocked: Backwards compatibility re-export detected. Instead of re-exporting, update all callers' import statements to point directly to the new location. Use Grep to find all imports of the old path, then update each call site." >&2
  exit 2
fi

# Check CSS files
if [[ "$file_path" =~ \.(css|scss|sass|less)$ ]]; then
  # Check trailing whitespace in CSS
  if echo "$content" | grep -qE '[[:blank:]]$'; then
    echo "Blocked: Trailing whitespace detected in CSS. Remove trailing spaces/tabs." >&2
    exit 2
  fi
  exit 0
fi

# Only check TypeScript files

if [[ ! "$file_path" =~ \.(ts|tsx)$ ]]; then
  exit 0
fi

# Check 1: Block barrel files (index.ts/js with only imports and exports)
basename=$(basename "$file_path")
if [[ "$basename" =~ ^index\.(ts|tsx)$ ]]; then
  # Remove single-line comments
  code=$(echo "$content" | sed 's|//.*$||g')

  # Remove 'use strict/client/server' directives
  code=$(echo "$code" | grep -vE "^['\"]use (strict|client|server)['\"];?\s*$")

  # Remove empty lines
  code=$(echo "$code" | sed '/^\s*$/d')

  if [ -n "$code" ]; then
    # Filter out:
    # - Lines starting with import or export keywords
    # - Continuation lines: braces, parentheses, commas, semicolons only
    # - Named items in multi-line imports/exports: just identifiers with optional commas/types
    has_logic=$(echo "$code" | \
      grep -vE '^\s*(import|export)\b' | \
      grep -vE '^\s*[{}(),;]+\s*$' | \
      grep -vE '^\s*(type\s+)?\w+\s*(as\s+\w+)?\s*,?\s*$' | \
      grep -vE '^\s*\*\s*(as\s+\w+)?\s*,?\s*$' | \
      grep -vE "^\s*['\"][^'\"]+['\"]\s*[,;]?\s*$" | \
      grep -vE '^\s*$')

    if [ -z "$has_logic" ]; then
      # No real code found - check we actually have imports or exports
      if echo "$code" | grep -qE '^\s*(import|export)\b'; then
        echo "Blocked: Barrel file (index.ts/js with only imports/exports). Import directly from source modules." >&2
        exit 2
      fi
    fi
  fi
fi

# Check 2: Block 'any' type usage
if echo "$content" | grep -qE ':\s*any\b|<any>|as\s+any\b'; then
  echo "Blocked: 'any' type detected. Use a specific type, 'unknown', or a generic instead." >&2
  exit 2
fi

# Check 3: Block bridge casting (as unknown as)
if echo "$content" | grep -qE 'as\s+unknown\s+as\b'; then
  echo "Blocked: Bridge cast 'as unknown as' detected. Fix the type system instead of forcing casts." >&2
  exit 2
fi

# Check 4: Block parent relative imports (../)
if echo "$content" | grep -qE "(import|from)\s+['\"]\.\.\/"; then
  echo "Blocked: Parent relative import '../' detected. Use path aliases (e.g., @/some/path) instead." >&2
  exit 2
fi

# Check 5: Block TypeScript suppression comments
if echo "$content" | grep -qE '@ts-ignore|@ts-expect-error|@ts-nocheck'; then
  echo "Blocked: TypeScript suppression comment detected. Fix the type error instead of suppressing it." >&2
  exit 2
fi

# Check 6: Block linter suppression comments
if echo "$content" | grep -qE 'eslint-disable|oxlint-disable|oxlint-ignore|tslint:disable|biome-ignore|prettier-ignore|noqa|noinspection'; then
  echo "Blocked: Linter suppression comment detected. Fix the lint error instead of suppressing it." >&2
  exit 2
fi

# Check 7: Block inline comments (comments on same line as code)
# Matches lines with code followed by // comment, but not:
# - Lines that are only comments (starting with //)
# - URLs containing ://
# - JSDoc lines (starting with *)
# Strip carriage returns for Windows compatibility (CRLF -> LF)
clean_content=$(printf '%s' "$content" | tr -d '\r')

# Find lines with inline comments:
# - \S.* ensures there's actual code (non-whitespace) before the comment
# - [^:]// ensures we don't match URLs like https://
inline_comment_lines=$(printf '%s' "$clean_content" | \
  grep -vE '^\s*//' | \
  grep -vE '^\s*\*' | \
  grep -E '\S.*[^:]//')

if [ -n "$inline_comment_lines" ]; then
  echo "Blocked: Inline comment detected. Place comments on their own line above the code." >&2
  exit 2
fi

# Check 8: Block console.* statements (log, error, warn, info, debug, trace, dir, etc.)
if echo "$content" | grep -qE '\bconsole\.(log|error|warn|info|debug|trace|dir|table|time|timeEnd|group|groupEnd|count|assert)\s*\('; then
  echo "Blocked: console.* statement detected. Use a proper logger (e.g., tslog, pino, winston) instead." >&2
  exit 2
fi

# Check 9: Block eval() and new Function()
if echo "$content" | grep -qE '\beval\s*\(|new\s+Function\s*\('; then
  echo "Blocked: eval() or new Function() detected. These are security risks. Use safer alternatives." >&2
  exit 2
fi

# Check 10: Block document.write()
if echo "$content" | grep -qE '\bdocument\.write\s*\('; then
  echo "Blocked: document.write() detected. Use DOM manipulation methods instead." >&2
  exit 2
fi

# Check 11: Block innerHTML assignment (XSS risk)
if echo "$content" | grep -qE '\.innerHTML\s*='; then
  echo "Blocked: innerHTML assignment detected. Use textContent or sanitize input to prevent XSS." >&2
  exit 2
fi

# Check 12: Block dangerouslySetInnerHTML without sanitization
if echo "$content" | grep -qE 'dangerouslySetInnerHTML'; then
  echo "Blocked: dangerouslySetInnerHTML detected. Sanitize content with DOMPurify or similar." >&2
  exit 2
fi

# Check 13: Block loose equality (== and !=) - should use === and !==
if echo "$content" | grep -qE '[^!=]=[^=]' | grep -qvE '===|!==|=>|<=|>='; then
  # More precise check: match == or != that aren't === or !==
  if echo "$content" | grep -qE '[^!<>=]==[^=]|[^!]=!=[^=]'; then
    echo "Blocked: Loose equality (== or !=) detected. Use strict equality (=== or !==) instead." >&2
    exit 2
  fi
fi

# Check 14: Block var declarations (use let or const)
if echo "$content" | grep -qE '^\s*var\s+|\bvar\s+'; then
  echo "Blocked: 'var' declaration detected. Use 'let' or 'const' instead." >&2
  exit 2
fi

# Check 15: Block improper catch blocks (errors must be captured and handled)
# 15a: Block parameterless catch blocks (catch { } without error param - modern JS/TS allows this)
if echo "$content" | grep -qE 'catch\s*\{'; then
  echo "Blocked: Parameterless catch block detected. Always capture the error: catch (error) { logger.error(error); ... }" >&2
  exit 2
fi

# 15b: Block catch blocks with unused error parameter (underscore prefix convention)
# Matches: catch (_), catch (_e), catch (_error), catch (_: Error), catch (_e: unknown), etc.
if echo "$content" | grep -qE 'catch\s*\(\s*_\w*(\s*:\s*[^)]+)?\s*\)'; then
  echo "Blocked: Catch with unused error parameter (_) detected. Errors must be logged: catch (error) { logger.error(error); ... }" >&2
  exit 2
fi

# 15c: Block empty catch blocks
if echo "$content" | grep -qE 'catch\s*\([^)]*\)\s*\{\s*\}'; then
  echo "Blocked: Empty catch block detected. Handle errors or log them, don't swallow silently." >&2
  exit 2
fi

# 15d: Block .catch() with parameterless callback (error not captured)
# Matches: .catch(() => ...), .catch(async () => ...), .catch(function() {...}), .catch(async function() {...})
if echo "$content" | grep -qE '\.catch\s*\(\s*(async\s+)?(\(\s*\)\s*=>|function\s*\(\s*\)\s*\{)'; then
  echo "Blocked: .catch() with parameterless callback. Always capture the error: .catch((error) => { logger.error(error); })" >&2
  exit 2
fi

# 15e: Block .catch() with unused error parameter (underscore prefix)
# Matches: .catch((_err) => ...), .catch(_err => ...), .catch(function(_err) {...})
if echo "$content" | grep -qE '\.catch\s*\(\s*(async\s+)?(\(\s*_[^)]*\)\s*=>|_\w*\s*=>|function\s*\(\s*_[^)]*\)\s*\{)'; then
  echo "Blocked: .catch() with unused error parameter (_). Errors must be logged: .catch((error) => { logger.error(error); })" >&2
  exit 2
fi

# 15f: Block .catch() with empty handler body
# Matches: .catch((err) => {}), .catch(function(err) {})
if echo "$content" | grep -qE '\.catch\s*\(.*=>\s*\{\s*\}\s*\)|\.catch\s*\(\s*(async\s+)?function[^{]*\{\s*\}\s*\)'; then
  echo "Blocked: Empty .catch() handler. Handle errors or log them: .catch((error) => { logger.error(error); })" >&2
  exit 2
fi

# Check 16: Block setTimeout/setInterval with string argument
if echo "$content" | grep -qE 'setTimeout\s*\(\s*["\x27]|setInterval\s*\(\s*["\x27]'; then
  echo "Blocked: setTimeout/setInterval with string argument detected. Pass a function instead." >&2
  exit 2
fi

# Check 17: Block .only() and .skip() in tests
if echo "$content" | grep -qE '\.(only|skip)\s*\(|it\.only|it\.skip|test\.only|test\.skip|describe\.only|describe\.skip'; then
  echo "Blocked: .only() or .skip() in test detected. Remove before committing." >&2
  exit 2
fi

# Check 18: Block hardcoded secrets/API keys
if echo "$content" | grep -qE 'AKIA[0-9A-Z]{16}|sk-[a-zA-Z0-9]{48}|ghp_[a-zA-Z0-9]{36}|gho_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{22,}'; then
  echo "Blocked: Hardcoded secret/API key detected. Use environment variables instead." >&2
  exit 2
fi

# Check 19: Block password/secret/apikey string assignments
if echo "$content" | grep -qiE '(password|secret|api_?key|auth_?token)\s*[:=]\s*["\x27][^"\x27]{8,}["\x27]'; then
  echo "Blocked: Hardcoded password/secret detected. Use environment variables instead." >&2
  exit 2
fi

# Check 20: Block array index as React key
if echo "$content" | grep -qE 'key\s*=\s*\{\s*(index|i|idx)\s*\}'; then
  echo "Blocked: Array index used as React key. Use a stable unique identifier instead." >&2
  exit 2
fi

# Check 21: Block SQL string concatenation (SQL injection risk)
# Only blocks explicit string concatenation with + operator.
# Does NOT block template literal ${} interpolation since tagged templates
# like Drizzle's sql`...${param}` are safe (auto-parameterized).
if echo "$content" | grep -qE '(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE).*\+\s*[a-zA-Z_]'; then
  echo "Blocked: SQL string concatenation detected. Use parameterized queries to prevent SQL injection." >&2
  exit 2
fi

# Check 22: Block TODO/FIXME/HACK comments
if echo "$content" | grep -qE '//\s*(TODO|FIXME|HACK|XXX)\b|/\*\s*(TODO|FIXME|HACK|XXX)\b'; then
  echo "Blocked: TODO/FIXME/HACK comment detected. Resolve before committing or create an issue." >&2
  exit 2
fi

# Check 23: Block trailing whitespace
if echo "$content" | grep -qE '[[:blank:]]$'; then
  echo "Blocked: Trailing whitespace detected. Remove trailing spaces/tabs." >&2
  exit 2
fi

# Check 24: Block missing newline at end of file
if [ -n "$content" ] && [ "$(echo "$content" | tail -c 1)" != "" ]; then
  last_char=$(printf '%s' "$content" | tail -c 1)
  if [ "$last_char" != $'\n' ]; then
    echo "Blocked: File does not end with a newline. Add a newline at the end." >&2
    exit 2
  fi
fi

# Check 25: Block debugger statements
if echo "$content" | grep -qE '^\s*debugger\s*;?\s*$|\bdebugger\b'; then
  echo "Blocked: 'debugger' statement detected. Remove before committing." >&2
  exit 2
fi

# Check 26: Block alert/confirm/prompt
if echo "$content" | grep -qE '\b(alert|confirm|prompt)\s*\('; then
  echo "Blocked: alert()/confirm()/prompt() detected. Use proper UI modals instead." >&2
  exit 2
fi

# Check 27: Block with statement
if echo "$content" | grep -qE '\bwith\s*\('; then
  echo "Blocked: 'with' statement detected. This is deprecated and confusing. Access properties directly." >&2
  exit 2
fi

# Check 28: Block throwing non-Error objects
if echo "$content" | grep -qE 'throw\s+["\x27]|throw\s+[0-9]|throw\s+true|throw\s+false|throw\s+null|throw\s+undefined'; then
  echo "Blocked: Throwing non-Error object detected. Always throw Error instances (throw new Error(...))." >&2
  exit 2
fi

# Check 29: Block forceUpdate() in React
if echo "$content" | grep -qE '\.forceUpdate\s*\(|this\.forceUpdate'; then
  echo "Blocked: forceUpdate() detected. Use proper state management to trigger re-renders." >&2
  exit 2
fi

# Check 30: Block direct DOM manipulation in React files
if [[ "$file_path" =~ \.tsx$ ]]; then
  if echo "$content" | grep -qE 'document\.(getElementById|getElementsByClassName|getElementsByTagName|querySelector|querySelectorAll)\s*\('; then
    echo "Blocked: Direct DOM manipulation in React component. Use refs or React state instead." >&2
    exit 2
  fi
fi

# Check 31: Block expect() without assertion in test files
if [[ "$file_path" =~ \.(test|spec)\.(ts|tsx)$ ]]; then
  if echo "$content" | grep -qE 'expect\s*\([^)]+\)\s*;?\s*$' | grep -qvE '\.(toBe|toEqual|toMatch|toContain|toThrow|toHaveBeenCalled|toHaveLength|toBeTruthy|toBeFalsy|toBeNull|toBeUndefined|toBeDefined|toBeGreaterThan|toBeLessThan|toBeInstanceOf|toHaveProperty|toHaveBeenCalledWith|toMatchSnapshot|toMatchInlineSnapshot|resolves|rejects)'; then
    echo "Blocked: expect() without assertion detected. Add an assertion like .toBe(), .toEqual(), etc." >&2
    exit 2
  fi
fi

# Check 32: Block native fetch() usage - use ky or axios instead
if echo "$content" | grep -qE '\bfetch\s*\('; then
  echo "Blocked: Native fetch() detected. Use ky (https://github.com/sindresorhus/ky) or axios instead for better error handling, retries, and interceptors." >&2
  exit 2
fi

# Check 33: Block deprecated Zod v4 methods (only in files importing zod)
# See: https://zod.dev/v4/changelog#deprecates-strict-and-passthrough
if echo "$content" | grep -qE "from\s+['\"]zod['\"]|require\s*\(\s*['\"]zod['\"]"; then
  if echo "$content" | grep -qE '\.strict\s*\('; then
    echo "Blocked: Deprecated Zod .strict() detected. Use z.strictObject({...}) instead. See https://zod.dev/v4/changelog" >&2
    exit 2
  fi
  if echo "$content" | grep -qE '\.passthrough\s*\('; then
    echo "Blocked: Deprecated Zod .passthrough() detected. Use z.looseObject({...}) instead. See https://zod.dev/v4/changelog" >&2
    exit 2
  fi
  if echo "$content" | grep -qE '\.strip\s*\('; then
    echo "Blocked: Deprecated Zod .strip() detected. Stripping unknown keys is the default in Zod v4 - remove the call. See https://zod.dev/v4/changelog" >&2
    exit 2
  fi
  if echo "$content" | grep -qE '\.merge\s*\('; then
    echo "Blocked: Deprecated Zod .merge() detected. Use .extend() instead. See https://zod.dev/v4/changelog" >&2
    exit 2
  fi
  if echo "$content" | grep -qE '\.deepPartial\s*\('; then
    echo "Blocked: Removed Zod .deepPartial() detected. This was removed in Zod v4 - restructure your schema. See https://zod.dev/v4/changelog" >&2
    exit 2
  fi
fi

# Check 34: Block stored logger references (react-fyre project only)
# Loggers should be resolved at call sites, not passed as parameters or stored as members.
if [[ "$file_path" == *"react-fyre"* ]]; then
  if echo "$content" | grep -qE '(private|protected)\s+(readonly\s+)?\w*[Ll]ogger\b'; then
    echo "Blocked: Stored logger reference detected (private/protected member). Resolve loggers at call sites instead of storing references." >&2
    exit 2
  fi
  if echo "$content" | grep -qE 'this\.\w*[Ll]ogger\s*='; then
    echo "Blocked: Logger instance assignment detected. Resolve loggers at call sites instead of storing references on 'this'." >&2
    exit 2
  fi
fi

exit 0
