// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitchArchivist.Persistence;

#nullable disable

namespace TwitchArchivist.Persistence.Migrations
{
    [DbContext(typeof(TwitchArchivistDbContext))]
    [Migration("20260428212555_AddEventSubConduitState")]
    partial class AddEventSubConduitState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.ArchiveJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("VodId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelConfigurationId");

                    b.ToTable("ArchiveJobs");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.ChannelConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPruneEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoPruneVodCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TwitchLogin")
                        .IsUnique();

                    b.ToTable("ChannelConfigurations");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubConduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShardCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwitchConduitId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TwitchConduitId")
                        .IsUnique();

                    b.ToTable("EventSubConduits");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubConduitShard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventSubConduitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAssignmentUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastWelcomeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventSubConduitId", "ShardId")
                        .IsUnique();

                    b.ToTable("EventSubConduitShards");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubSubscriptionBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventSubConduitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventSubConduitId");

                    b.HasIndex("ChannelConfigurationId", "SubscriptionType")
                        .IsUnique();

                    b.ToTable("EventSubSubscriptionBindings");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubscriptionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelConfigurationId", "SubscriptionType")
                        .IsUnique();

                    b.ToTable("EventSubscriptionStates");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.StreamSessionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownStreamId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastOfflineUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastOnlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastProcessedOfflineMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelConfigurationId")
                        .IsUnique();

                    b.ToTable("StreamSessionStates");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.TwitchOAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitchUserLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TwitchOAuthTokens");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.ArchiveJob", b =>
                {
                    b.HasOne("TwitchArchivist.Persistence.Entities.ChannelConfiguration", "ChannelConfiguration")
                        .WithMany("ArchiveJobs")
                        .HasForeignKey("ChannelConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelConfiguration");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubConduitShard", b =>
                {
                    b.HasOne("TwitchArchivist.Persistence.Entities.EventSubConduit", "EventSubConduit")
                        .WithMany("Shards")
                        .HasForeignKey("EventSubConduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSubConduit");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubSubscriptionBinding", b =>
                {
                    b.HasOne("TwitchArchivist.Persistence.Entities.ChannelConfiguration", "ChannelConfiguration")
                        .WithMany()
                        .HasForeignKey("ChannelConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitchArchivist.Persistence.Entities.EventSubConduit", "EventSubConduit")
                        .WithMany("SubscriptionBindings")
                        .HasForeignKey("EventSubConduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelConfiguration");

                    b.Navigation("EventSubConduit");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubscriptionState", b =>
                {
                    b.HasOne("TwitchArchivist.Persistence.Entities.ChannelConfiguration", "ChannelConfiguration")
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("ChannelConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelConfiguration");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.StreamSessionState", b =>
                {
                    b.HasOne("TwitchArchivist.Persistence.Entities.ChannelConfiguration", "ChannelConfiguration")
                        .WithOne("StreamSessionState")
                        .HasForeignKey("TwitchArchivist.Persistence.Entities.StreamSessionState", "ChannelConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelConfiguration");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.ChannelConfiguration", b =>
                {
                    b.Navigation("ArchiveJobs");

                    b.Navigation("EventSubscriptions");

                    b.Navigation("StreamSessionState");
                });

            modelBuilder.Entity("TwitchArchivist.Persistence.Entities.EventSubConduit", b =>
                {
                    b.Navigation("Shards");

                    b.Navigation("SubscriptionBindings");
                });
#pragma warning restore 612, 618
        }
    }
}
